name: ResidenceGUI
main: com.ranmc.residence.gui.Main
description: '桃花源定制24k纯钛合金超级无敌终终终终极版的领地菜单插件'
website: https://www.ranmc.cc/
author: Ranica
version: Beta 2.4
api-version: "1.20"
softdepend: [Residence,Ranmc]

permissions: 
  resgui.admin:
    default: op
    description: 'admin only'

  resgui.user:
    default: true
    description: 'user only'

commands:
  resgui:
    description: resgui
    usage: /<command>